# Project-wide Gradle settings.
# Configuración de memoria para Gradle
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true

# Habilita AndroidX (obligatorio para eliminar el error)
android.useAndroidX=true

# Convierte automáticamente librerías de soporte a AndroidX
android.enableJetifier=true

# Opcional: reduce el tiempo de compilación evitando R.class no transitivo
android.nonTransitiveRClass=false